# Generated by Django 4.0.2 on 2022-02-13 11:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postview_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=blog.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
